name: Sync to Hugging Face
on:
  push:
    branches: [main]
  force_push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Ganti 'username/space-name' dengan username dan nama Space Anda di Hugging Face
          # Gunakan format git remote add hf https://username:$HF_TOKEN@huggingface.co/spaces/username/spacename
          git remote add hf https://hernataramadhan79-bit:$HF_TOKEN@huggingface.co/spaces/hernataramadhan79-bit/ai-orbit-backend
          git push --force hf main
